apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-manager
  template:
    metadata:
      labels:
        app: task-manager
    spec:
      containers:
        - name: backend
          image: backend:latest
          ports:
            - containerPort: 5000
        - name: frontend
          image: frontend:latest
          ports:
            - containerPort: 3000
